[package]
name = "galois_fields"
version = "0.1.0"
edition = "2021"
authors = ["CÃ©sar Sagaert <sagaert.cesar@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
